### ISSUE TITLE
使用体验反馈：20231207版本

### ISSUE THREAD

**Issue by zengmenglu** [movetobe/FocusOn#1]
### 描述

体验FocusOnTodoList 20231207版本时，有一些体验待提升的地方。

### 复现步骤

1. 下载安装包，安装包没有版本号标识，与版本迭代更新日志。

2. 在macos双击应用程序，icon在macos顶部菜单栏不够显眼，导致我双击应用程序时，以为程序没有打开，双击了好几次。下图对比可以看到，其余app的icon有做反色，当背景为深色时，icon颜色显示为浅色。

macos非全屏状态下：
<img width="1468" alt="image" src="https://github.com/movetobe/FocusOnTodoList/assets/20340016/231c2498-067e-44fa-8a78-8d7cec715d0c">

macos全屏状态下：
<img width="1470" alt="image" src="https://github.com/movetobe/FocusOnTodoList/assets/20340016/3e54ab29-746f-4275-9a42-b3955780beb7">

3.  当已经开始计时时，不可以修改每天的总时间计划。但我认为这两个是独立的，开始计时，并不应该影响设置每天的总时间计划。
<img width="250" alt="image" src="https://github.com/movetobe/FocusOnTodoList/assets/20340016/a479d1e4-2ba1-401c-872f-738cd0f2f1ab">

4. 退出按钮设计不符合用户习惯，点击左上角按钮时，没有提示这个按钮是什么功能，结果程序退出，我还以为是闪退了。

<img width="58" alt="image" src="https://github.com/movetobe/FocusOnTodoList/assets/20340016/f9758f0e-6868-4993-a13f-49e1ab67260e">

### 期望行为

1. 安装包或可执行文件可以看到版本相关信息。后续上架应用市场时，app内可以检查更新，查看更新日志，并进行更新。

2. icon颜色显示能做到自适应反色。

3. 单次计时与全天计时计划的设置应相互独立。

4. 退出按钮设计修改为更符合用户使用习惯的方式，要么增加icon hover提示，要么参考印象笔记，左上角为设置按钮，在设置按钮中进行版本更新，退出程序等行为。

<img width="376" alt="image" src="https://github.com/movetobe/FocusOnTodoList/assets/20340016/b9f5ca27-86ab-4709-903f-b682e961ae88">

### 环境信息

操作系统： macos 13.4(22F66)
FocusOnTodoList: 20231207版本

**Comment by zengmenglu** [comment]
新增反馈：

# 复现步骤

1. 当创建TODO任务时，回车后，输入框里内容会默认填充上一次输入的内容，我认为没有必要。

<img width="268" alt="image" src="https://github.com/movetobe/FocusOnTodoList/assets/20340016/e2cdea13-4e02-45cc-a3a0-4afce3718cf8">

**Comment by zengmenglu** [comment]
新增反馈：

# 复现步骤

1. 当电脑重启后，TODO list  被清空。

![image](https://github.com/movetobe/FocusOnTodoList/assets/20340016/4052ecfd-121d-4b9c-b172-145cf241fc06)

**Comment by zengmenglu** [comment]
新增反馈：

# 期望行为

希望增加功能可以 自动生成日/周/月/季/年度总结报表。

**Comment by zengmenglu** [comment]
新增反馈：

# 复现步骤

桌面为macos自带壁纸，在空桌面时，软件颜色不易分辨。

![image](https://github.com/movetobe/FocusOnTodoList/assets/20340016/83f0217b-9003-46ac-a0d1-f0e368160b61)

**Comment by movetobe** [comment]
> ### 描述
> 体验FocusOnTodoList 20231207版本时，有一些体验待提升的地方。
> 
> ### 复现步骤
> 1. 下载安装包，安装包没有版本号标识，与版本迭代更新日志。
> 2. 在macos双击应用程序，icon在macos顶部菜单栏不够显眼，导致我双击应用程序时，以为程序没有打开，双击了好几次。下图对比可以看到，其余app的icon有做反色，当背景为深色时，icon颜色显示为浅色。
> 
> macos非全屏状态下： <img alt="image" width="1468" src="https://private-user-images.githubusercontent.com/20340016/288597947-231c2498-067e-44fa-8a78-8d7cec715d0c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2OTE5NDEsIm5iZiI6MTcwMzY5MTY0MSwicGF0aCI6Ii8yMDM0MDAxNi8yODg1OTc5NDctMjMxYzI0OTgtMDY3ZS00NGZhLThhNzgtOGQ3Y2VjNzE1ZDBjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI3VDE1NDA0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5ODA1ZGNmZDg0YzBiMmM2Mzg1NGMyNWU3MzA1OTYyYTE0MDM3OTliZjdhNjQ1ODBlODAyM2U3OTk1NWM4ZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WYgbb7ErWYPcOzbuAh4rr06r3Ip9W26dkrDJAiblsJ4">
> 
> macos全屏状态下： <img alt="image" width="1470" src="https://private-user-images.githubusercontent.com/20340016/288598634-3e54ab29-746f-4275-9a42-b3955780beb7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2OTE5NDEsIm5iZiI6MTcwMzY5MTY0MSwicGF0aCI6Ii8yMDM0MDAxNi8yODg1OTg2MzQtM2U1NGFiMjktNzQ2Zi00Mjc1LTlhNDItYjM5NTU3ODBiZWI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI3VDE1NDA0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5NjVhZDMxNjljODA3NTA5MWNjMTM5NTAxOThiMjRkODQwNWU3MWY2YTM1YTg1Njk0ODI4MjJhNWY0NWVhY2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.W59Sq-FH_xGSO2bI09cE4ZN1H1F3TEFoEclePsU5Wi8">
> 
> 3. 当已经开始计时时，不可以修改每天的总时间计划。但我认为这两个是独立的，开始计时，并不应该影响设置每天的总时间计划。
> 
> <img alt="image" width="250" src="https://private-user-images.githubusercontent.com/20340016/288599633-a479d1e4-2ba1-401c-872f-738cd0f2f1ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2OTE5NDEsIm5iZiI6MTcwMzY5MTY0MSwicGF0aCI6Ii8yMDM0MDAxNi8yODg1OTk2MzMtYTQ3OWQxZTQtMmJhMS00MDFjLTg3MmYtNzM4Y2QwZjJmMWFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI3VDE1NDA0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlZmFlZjQ3M2YwYmUxZTI5MWQwMTczMWI1ZThkYTkyZTJmZTk2NTZiNGVjZmQ3ZDZhMzAzOWFhMWNiYWIzNjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iB2E9kzFFz2ZOnd5XA3ZqzdAstqulOJVO0q7a9h-FAU">
> 4. 退出按钮设计不符合用户习惯，点击左上角按钮时，没有提示这个按钮是什么功能，结果程序退出，我还以为是闪退了。
> 
> <img alt="image" width="58" src="https://private-user-images.githubusercontent.com/20340016/288601998-f9758f0e-6868-4993-a13f-49e1ab67260e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2OTE5NDEsIm5iZiI6MTcwMzY5MTY0MSwicGF0aCI6Ii8yMDM0MDAxNi8yODg2MDE5OTgtZjk3NThmMGUtNjg2OC00OTkzLWExM2YtNDllMWFiNjcyNjBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI3VDE1NDA0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2OTA0NDAzNGUwM2JkOGNiYmQ0NDY0NjNkZmE3N2ZiODQxNjRhYzMzMzFlNmM5YmUzYzhkMzRiNThmMTRiMmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WKqfsOmgEZXCTGylNouyeSNY54DSHgnLO3CqL4RbGk4">
> ### 期望行为
> 1. 安装包或可执行文件可以看到版本相关信息。后续上架应用市场时，app内可以检查更新，查看更新日志，并进行更新。
> 2. icon颜色显示能做到自适应反色。
> 3. 单次计时与全天计时计划的设置应相互独立。
> 4. 退出按钮设计修改为更符合用户使用习惯的方式，要么增加icon hover提示，要么参考印象笔记，左上角为设置按钮，在设置按钮中进行版本更新，退出程序等行为。
> 
> <img alt="image" width="376" src="https://private-user-images.githubusercontent.com/20340016/288601454-b9f5ca27-86ab-4709-903f-b682e961ae88.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2OTE5NDEsIm5iZiI6MTcwMzY5MTY0MSwicGF0aCI6Ii8yMDM0MDAxNi8yODg2MDE0NTQtYjlmNWNhMjctODZhYi00NzA5LTkwM2YtYjY4MmU5NjFhZTg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI3VDE1NDA0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkMDc4MzAwNmQwOTU0MDYyN2Y1MzIwZDhjNDhkZjNjOGViNzY3OTNlZmMxYTZlOGJkYTg5MzI5OGVhYmM5NzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3GvM3zU5ut9VRsn5LVNKZzYRU7lEXz_QW-Wrp9DyveY">
> ### 环境信息
> 操作系统： macos 13.4(22F66) FocusOnTodoList: 20231207版本

DONE

**Comment by movetobe** [comment]
> 新增反馈：
> 
> # 复现步骤
> 1. 当创建TODO任务时，回车后，输入框里内容会默认填充上一次输入的内容，我认为没有必要。
> 
> <img alt="image" width="268" src="https://private-user-images.githubusercontent.com/20340016/289436890-e2cdea13-4e02-45cc-a3a0-4afce3718cf8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2OTE5NDEsIm5iZiI6MTcwMzY5MTY0MSwicGF0aCI6Ii8yMDM0MDAxNi8yODk0MzY4OTAtZTJjZGVhMTMtNGUwMi00NWNjLWEzYTAtNGFmY2UzNzE4Y2Y4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI3VDE1NDA0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxNGJkM2Y1MmM2N2M5OTIzZjM2NTA5ZTA3OTlhM2IzNTBkODQ4MDAwYzM3ZTZiYjZiNGQ0NGVhYmQwZjk0MGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JnUcrScAJMCHb8zmpySkqhszkBK-L_yZAd4yBOeS0JE">

DONE

**Comment by movetobe** [comment]
> 新增反馈：
> 
> # 复现步骤
> 桌面为macos自带壁纸，在空桌面时，软件颜色不易分辨。
> 
> ![image](https://private-user-images.githubusercontent.com/20340016/289785558-83f0217b-9003-46ac-a0d1-f0e368160b61.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2OTE5NDEsIm5iZiI6MTcwMzY5MTY0MSwicGF0aCI6Ii8yMDM0MDAxNi8yODk3ODU1NTgtODNmMDIxN2ItOTAwMy00NmFjLWEwZDEtZjBlMzY4MTYwYjYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI3VDE1NDA0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmNmI3MzY5MjNhNmJjZmExZmU1OGU2OGVkY2ZmMWI3ZGRjYTJjMjYzNWRhNzk1NjNlMTkzMGRmMDNjZDZiN2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.o6lx0GAGw88F3NBiyTecM-HmPiMGgcMkS507MJJ-jwM)

DONE

**Comment by movetobe** [comment]
添加年/月/周的问题另外开#issue2，其他已解决
